version: "2"
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - gochecknoinits
    - gocognit
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    revive:
      enable-all-rules: true
      rules:
        - name: unused-receiver
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: add-constant
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: function-length
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: nested-structs
          disabled: true
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
    misspell:
      locale: US
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$